name: CI

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # Install dependencies without Nx Cloud
      - run: npm ci --legacy-peer-deps

      # Set SHAs with Nx (optional, if needed)
      - uses: nrwl/nx-set-shas@v4

      # Run affected commands without Nx Cloud
      # This will run lint, test, build, and e2e tasks only for affected projects
      - run: npx nx affected -t lint test build e2e-ci
